<?xml version="1.0" encoding="utf-8"?><Database Name="FutureShop" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=FutureShop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FutureShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PicPath" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Category_SubCategory" Member="SubCategories" ThisKey="CID" OtherKey="CID" Type="SubCategory" />
      <Association Name="Category_Product" Member="Products" ThisKey="CID" OtherKey="CID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategory" Member="SubCategories">
    <Type Name="SubCategory">
      <Column Name="SCID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCategoryName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PicPath" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="SubCategory_Product" Member="Products" ThisKey="SCID" OtherKey="SCID" Type="Product" />
      <Association Name="Category_SubCategory" Member="Category" ThisKey="CID" OtherKey="CID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PicPath" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TotalQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_DealOfDay" Member="DealOfDays" ThisKey="PID" OtherKey="PID" Type="DealOfDay" />
      <Association Name="Product_ProductOffer" Member="ProductOffers" ThisKey="PID" OtherKey="PID" Type="ProductOffer" />
      <Association Name="Category_Product" Member="Category" ThisKey="CID" OtherKey="CID" Type="Category" IsForeignKey="true" />
      <Association Name="SubCategory_Product" Member="SubCategory" ThisKey="SCID" OtherKey="SCID" Type="SubCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegionMapping" Member="RegionMappings">
    <Type Name="RegionMapping">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegionName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="RegionMapping_DisrictMapping" Member="DisrictMappings" ThisKey="RID" OtherKey="RID" Type="DisrictMapping" />
      <Association Name="RegionMapping_ShippingCharge" Member="ShippingCharges" ThisKey="RID" OtherKey="RID" Type="ShippingCharge" />
    </Type>
  </Table>
  <Table Name="dbo.DisrictMapping" Member="DisrictMappings">
    <Type Name="DisrictMapping">
      <Column Name="DID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="District" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="RegionMapping_DisrictMapping" Member="RegionMapping" ThisKey="RID" OtherKey="RID" Type="RegionMapping" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingCharges" Member="ShippingCharges">
    <Type Name="ShippingCharge">
      <Column Name="RID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Charges" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RegionMapping_ShippingCharge" Member="RegionMapping" ThisKey="RID" OtherKey="RID" Type="RegionMapping" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DealOfDay" Member="DealOfDays">
    <Type Name="DealOfDay">
      <Column Name="DID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TodaysDiscount_InPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountedPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TodaysDeal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Product_DealOfDay" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UpdatedDeals" Member="UpdatedDeals">
    <Type Name="UpdatedDeal">
      <Column Name="DID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TodaysDiscount_InPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscountedPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TodaysDeal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserRegister" Member="UserRegisters">
    <Type Name="UserRegister">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SQuestion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SAnswer" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NewsLetter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ModificationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PlanSelected" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PlanDuration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="UserRegister_Billingdetail" Member="Billingdetails" ThisKey="UserID" OtherKey="UserId" Type="Billingdetail" />
    </Type>
  </Table>
  <Table Name="dbo.ProductOffers" Member="ProductOffers">
    <Type Name="ProductOffer">
      <Column Name="OfferID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Offer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Plans" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductOffer" Member="Product" ThisKey="PID" OtherKey="PID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schemes" Member="Schemes">
    <Type Name="Scheme">
      <Column Name="PlanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlanName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountInPercentage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlanDuration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlanImage" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Billingdetails" Member="Billingdetails">
    <Type Name="Billingdetail">
      <Column Name="BillingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ShippingAdd" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="District" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShippingCharges" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Billingdetail_OrderProductDetail" Member="OrderProductDetails" ThisKey="BillingId" OtherKey="BillingID" Type="OrderProductDetail" />
      <Association Name="UserRegister_Billingdetail" Member="UserRegister" ThisKey="UserId" OtherKey="UserID" Type="UserRegister" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderProductDetails" Member="OrderProductDetails">
    <Type Name="OrderProductDetail">
      <Column Name="OPID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Billingdetail_OrderProductDetail" Member="Billingdetail" ThisKey="BillingID" OtherKey="BillingId" Type="Billingdetail" IsForeignKey="true" />
    </Type>
  </Table>
</Database>